### ISSUE TITLE
Support for PHP 8 in a public release

### ISSUE THREAD

**Issue by evang522** [Speicher210/business-hours#1]
Hi guys, thanks for the great package. 

Is it possible you could make a release with PHP 8 support on your 2.* branch?  (or even 3.0, but I'm not sure about the plans for releasing this).  Just browsing through the code I don't see any reason why the latest release of v2 wouldn't be compatible with PHP 8, but I could be wrong. 

Thanks again.

**Comment by dragosprotung** [comment]
We should, but probably with version 3 only. There are a few more API braking changes that we want to do. Of course you can prepare a PR aganst current version 2 with PHP 8 support I am glad to review it release it

**Comment by evang522** [comment]
Yeah, I can definitely do that. Thanks -- just let me know which branch I should use.

**Comment by dragosprotung** [comment]
I have create `2.0` branch where you can bring support for PHP8.
You may bump min PHP version to 7.4 as well to make things easier.

TravisCI builds will not work anymore, you will have to add the github actions from master branch as well
